{
 "title": "HTTP Services",
 "tags": [ "Service" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(service_http_request_count_total, job)"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(service_http_request_count_total{exported_endpoint!~\"/metrics\", job=~\"$job\"}, exported_endpoint)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(service_http_request_count_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(service_http_request_count_total, status)"
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Service last updated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((time() - service_uptime{job=~\"$job\"}) * 1000)"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(service_uptime{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Request QPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_http_request_count_total{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Request success rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_http_request_count_total{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"^2.*\"}[$interval])) by (exported_endpoint) /sum(rate(service_http_request_count_total{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_http_request_size_bytes_sum{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)\n/\nsum(rate(service_http_request_size_bytes_count{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_http_request_duration_seconds_sum{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\r) by (exported_endpoint)\n/\r\nsum(rate(service_http_request_duration_seconds_count{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(service_http_request_duration_seconds_bucket{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_http_response_size_bytes_sum{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)\n/\nsum(rate(service_http_response_size_bytes_count{job=~\"$job\", exported_endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  }
 ]
}